### PR TITLE
resolved  #1 and added native support for Linux and Windows

### LINKED ISSUE #1: Risky Feeling for Users
Feels unreliable because system is asking for google account email and password.
Better to connect with running browser with already logged in account.

### PR DESCRIPTION
**Pull request by anurag3301**
Fixed the Password security issue. Now password won't appear on the screen as you type it. 
The program is made in the Windows system so it doesn't have direct support for Linux. I solved that also. 
@jaydeepdholakia the Windows path to the Webdriver doesn't seem fine, please check that also.

### CODE REVIEW

**Review by jaydeepdholakia — COMMENTED** [review]
Hey @anurag3301 can you make the alert (via the print) more normal? As any nonprogrammer should also understand what it means

**Comment by anurag3301** [comment]
@jaydeepdholakia I think you are talking about the password input. The `getpass` is a built-in module that is great for portability. I think you want to prompt `'*'` for each character as you enter the password. It is possible but then you have to introduce new dependencies such as `msvcrt` for window and `getch` for all OS and they also require some C++ dependencies. But as you are concern about the nonprogrammer, for them GUI will work the best.

BTW, I really liked the project and I am gonna add a lot of new features like GUI for more ease of use, Support for other channels so that people can use it to like other creators, and the issue I came across ie. Login for Two-Step Authentication

**Comment by anurag3301** [comment]
Now you can like other youtube creators also with Tanmay Bhatt

**Comment by anurag3301** [comment]
Add GUI for normal users. And added a special button for Tanmay Bhatt, as you click on that button, the URL of Tanmay's channel is automatically entered. 

@jaydeepdholakia check it once, and please let me know for any improvement.
Now I'm gonna work for two-step Auth.

**Comment by anurag3301** [comment]
Solved the issue of Two-Step Authentication problem using the code snippet `WebDriverWait(self.bot, 900).until(EC.presence_of_element_located((By.XPATH, "/html/body/header/div/div[1]/a[2]/span")))`. As you hit the Login button you are redirected to the StackOverflow page. Here this line of code is to hold the program until the StackOverflow page is detected. So if the Two-Step Authentication is enabled, the program will wait until the Two-Step Authentication is done and the complete login procedure is done.

**Review by sbdh11 — APPROVED** [review]

**Pull request closed without merging**
